/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class CelProgram {
  constructor()
  static compile(source: string): CelProgram
  execute(context: JsonValue): JsonValue
}
